#!/usr/bin/with-contenv bash
# shellcheck shell=bash

APP_MODULE="matchman.run:app"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec s6-notifyoncheck -d -n 300 -w 1000 \
        s6-setuidgid abc gunicorn --workers 4 --bind 0.0.0.0:3000 "$APP_MODULE"
else
    exec s6-notifyoncheck -d -n 300 -w 1000 \
        gunicorn --workers 4 --bind 0.0.0.0:3000 "$APP_MODULE"
fi
